### ISSUE TITLE
Card in "Eval post stage" impossible to close

### ISSUE THREAD

**Issue by atcrme** [cr-crme/banque_stages#15]
![Capture d’écran 2023-10-19 145000](https://github.com/cr-crme/banque_stages/assets/108420242/406f90c4-f436-495b-a3d9-26cb3358a051)

On Student page, Internship Screen, it is impossible to close the internship cards in the "Evaluation Post Stage" section.

**Comment by pariterre** [comment]
Cannot reproduce... I finished an internship and added a new one. Both are foldable.
