### ISSUE TITLE
Error with date format on internship form

### ISSUE THREAD

**Issue by atcrme** [cr-crme/banque_stages#16]
![image](https://github.com/cr-crme/banque_stages/assets/108420242/5df7e9ed-ada1-4bad-8f97-e6a961dd7b33)
![image](https://github.com/cr-crme/banque_stages/assets/108420242/02e0c7a6-20e1-4878-92b2-c02f2732c55b)
![image](https://github.com/cr-crme/banque_stages/assets/108420242/d3378dca-fa62-4220-b281-8a25ad42f856)

When using keyboard to add dates on the internship form, the date format showed as a hint is incorrect.
The correct format is : yyyy-mm-dd but the hint shows dd-mm-yyyy (in french)

**Comment by pariterre** [comment]
Fixed!
